version: '3'
services:
  app:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/damn_vulnerable_ecommerce

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
